### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by frederic-c-dcode** [Alamofire/AlamofireNetworkActivityIndicator#59]
Now that Xcode 11 supports Swift Package dependencies, it would be interesting to add the possibility to use this repository as Swift Package.

**Comment by Sam-Spencer** [comment]
Bump! Please!

**Comment by mthormann-dhi** [comment]
Because this library's Pod install depends on Alamofire base pod, I can't easily use Swift Package Manager for Alamofire and Pods for just this library until it is converted (since it will install another copy of Alamofire on top of the SwiftPM version).   This can be managed temporarily with a local podspec file like [this](https://stackoverflow.com/questions/40659236/is-it-possible-to-exclude-dependency-in-cocoapods), but that's really kludgy.

**Comment by yakovmanshin** [comment]
What about forking this repo and adding a temporary `Package.swift` file? Anyone tried it?

**Comment by Sam-Spencer** [comment]
[This branch](https://github.com/alphatroya/AlamofireNetworkActivityIndicator/tree/spm) of @ alphatroya's fork has SPM support.

**Comment by mthormann-dhi** [comment]
It failed CI checks.   It looks like the Travis config just needs to have iOS 9 support dropped since the CI server in use has no iOS 9 simulators installed

**Comment by jshier** [comment]
This can now be used by sourcing the `master` branch. It will officially go out in the next release.
